export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const SAVE_TASK_SUCCESS = "SAVE_TASK_SUCCESS";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_ALL_COMPLETED = "DELETE_ALL_COMPLETED";

// members action types
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const LOGIN_MEMBER_SUCCESS = "LOGIN_MEMBER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
