export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const SAVE_TASK_SUCCESS = "SAVE_TASK_SUCCESS";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_ALL_COMPLETED = "DELETE_ALL_COMPLETED";
export const MARK_TASK_COMPLETED = "MARK_TASK_COMPLETED";
// members action types
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const LOGIN_MEMBER_SUCCESS = "LOGIN_MEMBER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

// button status
export const CLICK_BUTTON_STATUS = "CLICK_BUTTON_STATUS";
export const CLICK_BUTTON_LOGOUT = "CLICK_BUTTON_LOGOUT";

// error status
export const HANDLE_ERROR_SUCCESS = "HANDLE_ERROR_SUCCESS";

// forgot password
export const FORGOT_PASSWORD_INPUT = "FORGOT_PASSWORD_INPUT";
